- id: doi:10.1038/s41746-026-03145-9
  image: images/publications/junxia_npjdm.png
  tags:
    - pan-hematology
    - image analysis
    - cellbytes

- id: doi:10.1002/hem3.70319
  image: images/publications/kata_hemasphere.png
  tags:
    - chronic myeloid leukemia
    - image analysis
    - cellbytes

- id: doi:10.1007/s00277-026-06863-y
  image: images/publications/theerin_ah.png
  tags:
    - acute myeloid leukemia
    - myelodysplastic
    - myelofibrosis
    - registry analysis
    
- id: doi:10.1002/cpt.70116
  image: images/publications/pkpd.jpg
  tags:
    - solid tumors
    - pkpd
    - registry analysis

- id: doi:10.1016/j.clml.2025.12.002
  image: images/publications/cll.jpg
  tags:
    - chronic lymphocytic leukemia
    - registry analysis

- id: doi:10.1016/j.esmorw.2025.100196
  image: images/publications/esmorwd.jpg
  tags:
    - myelofibrosis
    - risk scores
    - registry analysis
    
- id: doi:10.1038/s41375-025-02769-2
  image: images/publications/cml_mikko.png
  tags:
    - chronic myeloid leukemia
    - image analysis
    - cellbytes

- id: doi:10.1038/s41409-024-02374-4
  image: images/publications/gvhd.jpg
  tags:
    - graft-versus-host-disease
    - accessibility

- id: doi:10.3324/haematol.2024.286267
  image: images/publications/dlbcl_matias.jpg
  tags:
    - b-cell lymphoma
    - immunology
    - spatial image analysis
    
- id: doi:10.1186/s12961-024-01228-1
  image: images/publications/map.png
  tags:
    - research policy
    - data privacy

- id: doi:10.1182/blood.2023022740
  image: images/publications/blood_he.jpeg
  tags:
    - bone marrow
    - histopathology
    - computer vision

- id: doi:10.1038/s41592-024-02233-6
  image: images/publications/natmed_cellsegmentation.jpeg
  tags:
    - computer vision
    - cell segmentation

- id: doi:10.1038/s41408-022-00667-9
  image: images/publications/cml_shady.jpeg
  tags:
    - chronic myeloid leukemia
    - treatment-free remission
    - genetics
    
- id: doi:10.1038/s41375-022-01662-6
  image: images/publications/pyroptosis.jpeg
  tags:
    - acute myeloid leukemia
    - multiomics
    - immunology
  
- id: doi:10.2217/fon-2023-0120
  image: images/publications/mm.jpeg
  tags:
    - multiple myeloma
    - registry analysis
    - treatment patterns
    
- id: doi:10.1038/s43856-023-00418-2
  image: images/publications/geography.jpeg
  tags:
    - research policy
    - bibliometric analysis
    
- id: doi:10.1038/s41416-023-02329-4
  image: images/publications/rcc_immunology.jpeg
  tags:
    - renal cell carcinoma
    - computer vision
    - multiomics
    
- id: doi:10.1158/2643-3230.BCD-20-0162
  image: images/publications/mds_bcd.jpeg
  #date: 2021-5-1
  #extra-links:
  #  - type: manubot
  #    link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - computer vision
    - myelodysplastic syndrome
    - genetics

- id: doi:10.1016/j.ccell.2020.06.002
  image: images/publications/cancercell.jpeg
  tags:
    - hematology
    - big data
    - genetics
    - immunology
  ##repo: greenelab/meta-review
  #extra-links:
    #- type: manubot
    #  link: https://greenelab.github.io/meta-review/
    #- type: source
    #  link: https://github.com/greenelab/meta-review
    #- type: website
    #  link: http://manubot.org/

- id: doi:10.1038/s41379-021-00864-0
  image: images/publications/rcc.jpeg
  tags:
    - renal cell carcinoma
    - spatial image analysis
    - immunology

- id: doi:10.1158/2159-8290.CD-21-0410
  image: images/publications/ism2.jpeg
  tags:
    - acute myeloid leukemia
    - multiomics
    - drug sentivity screening

- id: doi:10.1182/bloodadvances.2019000792
  image: images/publications/aml_imm.jpeg
  tags:
    - acute myeloid leukemia
    - immunology
    - image analysis

- id: doi:10.1038/s41375-018-0360-1
  image: images/publications/ball_imm.jpeg
  tags:
    - acute lymphoid leukemia
    - immunology
    - image analysis

- id: doi:10.1038/s41375-018-0175-0
  image: images/publications/cml_imm.jpeg
  tags:
    - chronic myeloid leukemia
    - immunology
    - image analysis

- id: doi:10.1158/1078-0432.CCR-21-3140
  image: images/publications/dlbcl_imm.jpeg
  tags:
    - b-cell lymphoma
    - immunology
    - spatial image analysis