- id: doi:10.1158/2643-3230.BCD-20-0162
  image: images/MDS_unsupervised.tiff
  #date: 2021-5-1
  #extra-links:
  #  - type: manubot
  #    link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - computer vision
    - myelodysplastic syndrome
    - genetics

- id: doi:10.1016/j.ccell.2020.06.002
  image: images/cancercell.jpeg
  tags:
    - hematology
    - big data
    - genetics
  #repo: greenelab/meta-review
  #extra-links:
    #- type: manubot
    #  link: https://greenelab.github.io/meta-review/
    #- type: source
    #  link: https://github.com/greenelab/meta-review
    #- type: website
    #  link: http://manubot.org/

- id: doi:10.1158/2159-8290.CD-21-0410
  image: images/ism2.jpeg
  tags:
    - aml
    - multiomics
    - drug sentivity screening
