- id: doi:10.1158/2643-3230.BCD-20-0162
  type: paper
  image: images/publications/mds_bcd.jpeg
  #description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  #date: 2021-5-1
  #repo: greenelab/meta-review
  #buttons:
  #  - type: manubot
  #    link: https://greenelab.github.io/meta-review/
  #  - type: source
  #    text: Manuscript Source
  #    link: https://github.com/greenelab/meta-review
  #  - type: website
  #    link: http://manubot.org/
  tags:
    - computer vision
    - myelodysplastic syndrome
    - genetics

- id: doi:10.1016/j.ccell.2020.06.002
  image: images/publications/cancercell.jpeg
  tags:
    - hematology
    - big data
    - genetics
    - immunology

- id: doi:10.1038/s41379-021-00864-0
  image: images/publications/rcc.jpeg
  tags:
    - renal cell carcinoma
    - spatial image analysis
    - immunology

- id: doi:10.1158/2159-8290.CD-21-0410
  image: images/publications/ism2.jpeg
  tags:
    - acute myeloid leukemia
    - multiomics
    - drug sentivity screening

- id: doi:10.1182/bloodadvances.2019000792
  image: images/publications/aml_imm.jpeg
  tags:
    - acute myeloid leukemia
    - immunology
    - image analysis

- id: doi:10.1038/s41375-018-0360-1
  image: images/publications/ball_imm.jpeg
  tags:
    - acute lymphoid leukemia
    - immunology
    - image analysis

- id: doi:10.1038/s41375-018-0175-0
  image: images/publications/cml_imm.jpeg
  tags:
    - chronic myeloid leukemia
    - immunology
    - image analysis

- id: doi:10.1158/1078-0432.CCR-21-3140
  image: images/publications/dlbcl_imm.jpeg
  tags:
    - b-cell lymphoma
    - immunology
    - spatial image analysis